name: Build

on:
  push:
    branches:
    - main
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  build:
    strategy:
      matrix:
        type: [retail, wrath, classic, cata]
        include:
          - type: retail
            pkgmeta: .pkgmeta_retail
          - type: wrath
            pkgmeta: .pkgmeta_wrath
          - type: classic
            pkgmeta: .pkgmeta_vanilla
          - type: cata
            pkgmeta: .pkgmeta_cata

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@master
      with:
        args: -p 865814 -a nGvppv6x -g ${{matrix.type}} -m ${{matrix.pkgmeta}}
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
